### ISSUE TITLE
Got an error with the right Syntax

### ISSUE THREAD

**Issue by DonaldDuck007** [philsmd/7z2hashcat#1] opened 2016-08-12 21:41 UTC
I got a error, although i used the right Syntax and a "normal" .7z file
"**C:\path\to\7z2hashcat.pl C:\path\to\file.7z**"
=>
"**WARNING: could not open file 'C:\path\to\file.7z'**"

**Comment by philsmd** [comment] 2016-08-13 14:52
I'm not sure what the problem could be in this very specific case without being able to reproduce.
Most probably the file just doesn't exist at that location/path. Are you sure that the path is correct ?

What happens if you place the file in the current directory and if you do not use the C:\path\to\ part at all in your command line ? i.e.
perl 7z2hashcat.pl file.7z

(of course you need to first copy file.7z into the currect directory to perform this test)
thanks

**Comment by philsmd** [comment] 2016-12-30 10:36
I'm closing this issue because I didn't get any answer for this issue. It's very likely that this is a user problem because the 'WARNING: could not open file' warning only appears whenever the call to the file open () function fails (i.e. the file does not exist at that very specific location).

If you still think this is a problem of 7z2hashcat.pl, please reopen this issue and advice how I can reproduce this. Thank you very much

**Closed by philsmd** 2016-12-30 10:36 UTC
