### ISSUE TITLE
I get 'Token length exception' with hashcat 5.1.0

### ISSUE THREAD

**Issue by h4knet** [philsmd/7z2hashcat#27] opened 2020-06-09 11:22 UTC
Hello,
I've never used this tool before nor tried to crack 7z archives.
I've git cloned the project on latest Kali & ran ```apt install libcompress-raw-lzma-perl```.
Then I executed the script & obtained a 127kb output redirected into a file.

Is a 127kb file size normal ?

Regards,

**Comment by magnumripper** [comment] 2020-06-09 19:18
Have a look at all closed issues, nearly all of them is about this 😆

**Comment by philsmd** [comment] 2020-06-10 08:35
I think up to 320 KB are currently supported: https://github.com/philsmd/7z2hashcat/blob/fe0db6b0de75378ff3d3a3c66324178fa9437223/7z2hashcat.pl#L131 (320 KB * 2 to obtain the hexadecimal hash length).

Therefore, 127 KB seems to be less than the limit of hashcat.

I would advice you to test with the beta version of hashcat from https://hashcat.net/beta since it already has several changes since last release version of hashcat (also affecting hash type -m 11600 = 7-Zip).

If the latest **hashcat version** works for you, there is nothing we can do here and the next release version of hashcat will contain the fix (too). I would assume that if there is really something wrong with the .7z file, then also 7z2hashcat.pl should show you an error (it will also show you an error if the size is too long... so that shouldn't be the case, I guess). Thx

If latest **hashcat** version (beta, since it is much newer than release) solves the problem, please close the issue after testing.
If it's still not working, we probably would need to have an example .7z file and hash (but before posting hashes please test with the latest tools).
Thx

**Comment by philsmd** [comment] 2020-06-13 09:32
We didn't get any further response here, but it seems quite obvious that the problem is fixed by using the correct/updated tools. I will close this issue for now. Feel free to re-open if you have further details and the problem persists (even with the latest beta hashcat version etc)

**Closed by philsmd** 2020-06-13 09:32 UTC
